apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}-cfg
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- toYaml .Values.config | nindent 4 }}
